### ISSUE TITLE
Tons of warnings emitted when building with clang 13.0.1

### ISSUE THREAD

**Issue by lukekasz** [MolecularMatters/raw_pdb#29]
Due to the following code in PDB_Warnings.h, I get a 30+ warnings when compiling most of the .cpp files with clang 13.0.1

```c++
#elif PDB_COMPILER_CLANG
	// turn on absolutely all available Clang warnings
#	pragma clang diagnostic warning "-Wall"
#	pragma clang diagnostic warning "-Wextra"
#	pragma clang diagnostic warning "-Weverything"
#	pragma clang diagnostic warning "-Wpedantic"
...
```

I can fix the warnings by adding the following suppressions:

```c++
#   pragma clang diagnostic ignored "-Wextra-semi"
#   pragma clang diagnostic ignored "-Wzero-length-array"
#   pragma clang diagnostic ignored "-Wnewline-eof"
#   pragma clang diagnostic ignored "-Wreserved-identifier"
#   pragma clang diagnostic ignored "-Wused-but-marked-unused"
#   pragma clang diagnostic ignored "-Wmissing-field-initializers"
#   pragma clang diagnostic ignored "-Wmissing-prototypes"
``` 
Before I open a PR with these changes, I wondering if there is a reason for enabling all clang warnings and whether the code should be fixed instead or perhaps the warning levels should be relaxed? There are no warnings when building in VS2022.

**Comment by tivolo** [comment]
I'll have a look at whether those should/can be fixed or the warning level should be relaxed.
My gut feeling would be to keep as much warnings enabled as possible.

**Comment by MolecularMatters** [comment]
This should now be fixed in https://github.com/MolecularMatters/raw_pdb/commit/4ce21c146f0d410aba7cfe525d01f498133ff3df.
Please check with your version of Clang.

**Comment by lukekasz** [comment]
I can confirm that all clang 13.0.1 warnings are fixed in https://github.com/MolecularMatters/raw_pdb/commit/4ce21c146f0d410aba7cfe525d01f498133ff3df. Thanks!

Side-note: I do get these `printf` warnings, but I think they are related to how `printf` is declared in [MinGW-w64](https://www.mingw-w64.org/) or my setup somehow and not something specific to the code in this project.

```
src\Examples\ExampleMain.cpp:23:5: warning: 'printf' was marked unused but was used [-Wused-but-marked-unused]
                                printf("Invalid Superblock\n");
```
