### ISSUE TITLE
Crash when trying to read symbols from `LLVMCodeGen.pdb`

### ISSUE THREAD

**Issue by florian-kuebler** [MolecularMatters/raw_pdb#34]
When trying the "function symbol example" on the LLVMCodeGen.pdb (can be provided if necessary), there is a crash in `AreBlockIndicesContiguous` (`blockIndices` seem to be empty), when trying to call `CreateImageSectionStream`.

What is interesting: I added a `CHECK(dbiStream.HasValidImageSectionStream(rawPdbFile) == PDB::ErrorCode::Success);`, which succeeds.

When trying to open that PDB file with LLVM, `hasPDBDbiStream` is returning false.
The "dia2dump" example is printing a lot of function symbols, however, the "global function symbols" seem to be empty.

So maybe there is also something wrong with the pdb.

**Comment by MolecularMatters** [comment]
Thanks for the report.
Can you make the PDB available somewhere? I'd like to take a look and fix this.

**Comment by florian-kuebler** [comment]
[LLVMCodeGen.zip](https://github.com/MolecularMatters/raw_pdb/files/9422988/LLVMCodeGen.zip)

As said, this is quite special. It doesn't seem to have debug info nor public symbols. It corresponds to llvm's code gen ".lib", so it is probably expected. Still there should probably not be a crash.

**Comment by MolecularMatters** [comment]
Thank you for reporting this.
The issue has been fixed in df6f1ea06784a154b8242e9877efd1fd176db457.
