### ISSUE TITLE
Default MSFStream Type - CoalescedMSFStream vs DirectMSFStream

### ISSUE THREAD

**Issue by lukekasz** [MolecularMatters/raw_pdb#49]
I've hit a bit of an performance/memory usage issue with RawPDB.

I'm using the TPIStream with a 1.11 GB clang debug PDB and just creating the stream takes around 300 ms and uses around 240 MiB memory. The PDB has 2.962.141 type records and I only need to inspect some of them.

The issue is that the TPIStream uses CoalescedMSFStream internaly and the TPIStream in this PDB is not continuous, so the entire stream is read into memory block by block. This works great if you want to read all the type records. But I for my use case I would prefer to have it use DirectMSFStream instead and pay for the cost of reading the individual records lazily.

I'm looking for feedback on how to make a change to RawPDB that would support both use cases and fit with the overall design philosophy of the library.

Here are a some suggestions.

1. Somehow make TPIStream support both CoalescedMSFStream and DirectMSFStream. Perhaps at compile time with a template parameter or runtime with a flag?
2. Add a TPIDirectStream in addition to the existing TPIStream that uses DirectMSFStream.
3. Change TPIStream to use DirectMSFStream and make the user code/example read the type records they need and cache them there instead for fast lookup. E.g. moving the cost of reading all types from creation of the TPIStream in RawPDB to user code.

Also worth considering whether whatever approach is taken here could be used for other streams as well.

Look forward to hearing your thoughts :-)

**Comment by MolecularMatters** [comment]
I think it would be fine to make TPIStream use a DirectMSFStream, like the DBI stream does.
The IPIStream would then be the only one using a CoalescedMSFStream by default, but that's fine, since that stream normally isn't that large.

**Comment by lukekasz** [comment]
Great, thanks for the feedback. I will make the change and open a PR :-)
