### ISSUE TITLE
jpeg62.pdb   bug

### ISSUE THREAD

**Issue by icyfox168168** [MolecularMatters/raw_pdb#67]
Running example "Lines"
| | | Reading image section stream
| | | ---> done in 0.079ms
| | | Reading module info stream
| | | ---> done in 0.131ms
| | | Reading names stream
| | | ---> done in 0.133ms
| | | Storing lines from modules

https://ufile.io/jki1dcht

**Comment by MolecularMatters** [comment]
Can you please provide more information when submitting an issue?
The description says "jpeg62.pdb bug", but I don't see what's wrong.

It would be nice if you could describe what you're expecting to see, what's happening, what the actual bug is, etc.
