### ISSUE TITLE
I am not sure I understand the validity of PDB_NO_ALIAS

### ISSUE THREAD

**Issue by Scr3amer** [MolecularMatters/raw_pdb#69]
Hello !

I was trying to compile your project with llvm + MinGW, which requires some change in your code.

(I made it work so expect a PR soon :) )

I found the PDB_NO_ALIAS macro but I am not sure I understand why it is correct in your use case because the pointer returned by ArrayView::Decay is the same as the one provided to its constructor so it is an alias ?

Or did I misunderstand the very definition of aliasing ?

Cheers,
Scr3am

**Comment by MolecularMatters** [comment]
I think you might be right about this.
It is probably best to get rid of PDB_NO_ALIAS completely, since it won't affect code generation much anyway.

In cases where aliasing really could be a problem, using local variables on the stack is a much better solution.

**Comment by MolecularMatters** [comment]
I removed PDB_NO_ALIAS in 3c224f6.
