### ISSUE TITLE
Support for function parameters

### ISSUE THREAD

**Issue by pierricgimmig** [MolecularMatters/raw_pdb#7]
It seems there is no support for function parameters when enumerating function symbols. This would be a great addition to identify overloaded functions for example.

**Comment by MolecularMatters** [comment]
All function symbols like e.g. S_LPROC, S_GPROC store a typeIndex, which indexes a type in the TPI stream.
However, there is no TPI stream support yet, but it shouldn't be too hard to add that in the future.

**Comment by MolecularMatters** [comment]
With support for TPI streams in da364670ae22d7a5be0215ebb3d31bca334c04b3, this should now be possible.
