### ISSUE TITLE
When the C++20 standard is selected for compilation, a warning appears

### ISSUE THREAD

**Issue by icyfox168168** [MolecularMatters/raw_pdb#84]
case PDB::CodeView::TPI::TypeRecordKind::LF_FIELDLIST:
			TagChildren(typeTable, record, setName);
                        break;  add is ok 

>(编译源文件“/src/Examples/ExampleTypes.cpp”)
1>C:\Users\HUAWEI\Desktop\raw_pdb\src\Examples\ExampleTypes.cpp(1249,3): warning C5262: 此处发生隐式失败；是否缺少中断语句? 当在事例之间有意省略中断语句时，请使用 [[fallthrough]]
1>(编译源文件“/src/Examples/ExampleTypes.cpp”)
1>    C:\Users\HUAWEI\Desktop\raw_pdb\src\Examples\ExampleTypes.cpp(1249,3):
1>    要简化迁移，请考虑暂时对用于生成且不引发警告的编译器版本使用 /Wv:18 标记
1>    C:\Users\HUAWEI\Desktop\raw_pdb\src\Examples\ExampleTypes.cpp(1248,4):
1>    可能失败的语句位于此处

template<typename T>
static void TagRecursively(const TypeTable& typeTable, uint32_t typeIndex, T setName)
{
	const PDB::CodeView::TPI::Record* record = typeTable.GetTypeRecord(typeIndex);
	if (!record)
		return;
	switch (record->header.kind)
	{
		case PDB::CodeView::TPI::TypeRecordKind::LF_ARRAY:
			TAG_AND_CHECK(record->data.LF_ARRAY.elemtype);
			TAG_AND_CHECK(record->data.LF_ARRAY.idxtype);
			break;
		case PDB::CodeView::TPI::TypeRecordKind::LF_POINTER:
			TAG_AND_CHECK(record->data.LF_POINTER.utype);
			break;
		case PDB::CodeView::TPI::TypeRecordKind::LF_MODIFIER:
			TAG_AND_CHECK(record->data.LF_MODIFIER.type);
			break;
		case PDB::CodeView::TPI::TypeRecordKind::LF_PROCEDURE:
			TAG_AND_CHECK(record->data.LF_PROCEDURE.rvtype);
			TAG_AND_CHECK(record->data.LF_PROCEDURE.arglist);
			break;
		case PDB::CodeView::TPI::TypeRecordKind::LF_ARGLIST:
		{
			size_t count = record->data.LF_ARGLIST.count;
			for (size_t i = 0; i < count; i++)
			{
				uint32_t type = record->data.LF_ARGLIST.arg[i];
				TAG_AND_CHECK(type);
			}
			break;
		}
		case PDB::CodeView::TPI::TypeRecordKind::LF_MFUNCTION:
			TAG_AND_CHECK(record->data.LF_MFUNCTION.rvtype);
			TAG_AND_CHECK(record->data.LF_MFUNCTION.arglist);
			TAG_AND_CHECK(record->data.LF_MFUNCTION.thistype);
			break;
		case PDB::CodeView::TPI::TypeRecordKind::LF_FIELDLIST:
			TagChildren(typeTable, record, setName);
		default:
			break;
	}
}

**Comment by MolecularMatters** [comment]
Thanks for reporting this, should be fixed in a0900400f0135fdea1d4b7c1790ccdff49a60095.
